# Generated by Django 4.0.10 on 2023-09-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_memberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
