# Generated by Django 4.0.10 on 2023-09-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_memberprofile_first_name_memberprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='member',
            name='location',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
    ]
